###login as author
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
    "email":"vivek@gmail.com",
    "password":"123456"
}

###login as user
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
    "email":"harish@gmail.com",
    "password":"123456"
}


###authenticate author
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
    "email":"vivek@gmail.com",
    "password":"123456"
}


###authenticate user
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
    "email":"vivek@gmail.com",
    "password":"123456"
}



###register user
POST http://localhost:4000/author-api/users
Content-Type: application/json

{
    "firstName":"vivek",
    "lastName":"kumar",
    "email":"vivek@gmail.com",
    "password":"123456"

}

###delete and restore
PATCH http://localhost:4000/author-api/articles/69ae9264ba3afd1a536ab450/status
Content-Type: application/json

{ "isArticleActive": true }


###create articles
POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "author":"69aef4f3a85d8f90eb532474",
    "title":"Javascript",
    "category":"programming",
    "content":"Java script is famous and most trending programing language in modern days"
}



###update articles
PUT http://localhost:4000/author-api/articles
Content-Type: application/json

{    
    "articleId":"69aef5eda85d8f90eb532484",
    "author":"69aef4f3a85d8f90eb532474",
    "title":"JavaScript",
    "category":"Programming",
    "content":"Java script is famous and most trending programing language in these days"

}

