GET http://localhost:3000/user-api/users


### Response
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "id": "100",
  "name": " Birzuu",
  "age": "20"
}

###
PUT http://localhost:3000/user-api/users/id
Content-Type: application/json

{
    "id": "100",
  "name": " Affu",
  "age": "21"
}   

### read user by id
GET http://localhost:3000/user-api/users/100


###
DELETE http://localhost:3000/user-api/users/100



###
GET http://localhost:3000/product-api/products

###
GET http://localhost:3000/product-api/products/:productId

###
GET http://localhost:3000/product-api/products-name/:name

###
POST http://localhost:3000/product-api/products
Content-Type: application/json

{
    "id": "200",
  "name": " Laptop",
  "brand": " Dell",
  "price": "50000"
}

###
PUT http://localhost:3000/product-api/products/:productId
Content-Type: application/json

{
    "id": "200",
  "name": " Laptop",
  "brand": " HP",
  "price": "55000"
}

###
DELETE http://localhost:3000/product-api/products/200
