### Create User
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "name":"",
    "email":"usera1@gmail.com",
    "dateOfBirth":"2000-12-21",
    "mobileNumber":7894561230
}

### read all users
GET http://localhost:3000/user-api/users

### read a user by id
GET http://localhost:3000/user-api/users/69a694c212c829cbfc74e32c

### delete a user by id
DELETE http://localhost:3000/user-api/users/69a694c212c829cbfc74e32c

### Activate user
PATCH http://localhost:3000/user-api/users/69a694c212c829cbfc74e32c